# ============================================================
#  Game:        Crash Bandicoot: The Wrath of Cortex
#  Region:      NTSC (USA)
#  GameID:      GCBE7D
#  System:      GameCube
#  Last update: 2026-09-29
# ============================================================
#  Same override as PAL version (GCBP7D). See that file for
#  detailed reasoning.
# ============================================================

[Core]
OverclockEnable = True
Overclock = 0.500000

[Video_Hardware]
ImmediatelyPresentXFB = False

[Video_Settings]
InternalResolution = 1
