# ============================================================
#  Game:        Dragon Ball Z: Budokai
#  Region:      NTSC (USA)
#  GameID:      GDBE69
#  System:      GameCube
#  Last update: 2026-09-29
# ============================================================
#  Same override as PAL version (GDBP69). See that file for
#  detailed reasoning.
# ============================================================

[Core]
OverclockEnable = True
Overclock = 0.600000

[Video_Hardware]
ImmediatelyPresentXFB = False

[Video_Settings]
InternalResolution = 1
