# Super Mario Strikers (NTSC) - override per-gioco
# Fonte: Dolphin H700/MuOS Compatibility List (Mercquick) - FPS 10-25, giocabile
[Core]
OverclockEnable = True
Overclock = 0.400000

[Video_Settings]
InternalResolution = 0.33
